# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='game',
  syntax='proto3',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\ngame.proto\x12\x04game\"D\n\x0e\x65ntity_message\x12\x10\n\x08\x65ntityID\x18\x01 \x01(\x05\x12\x12\n\nmethodName\x18\x02 \x01(\t\x12\x0c\n\x04parm\x18\x03 \x01(\x0c\"\x06\n\x04void2@\n\x0bGameService\x12\x31\n\rentity_method\x12\x14.game.entity_message\x1a\n.game.voidB\x03\x90\x01\x01\x62\x06proto3')
)




_ENTITY_MESSAGE = _descriptor.Descriptor(
  name='entity_message',
  full_name='game.entity_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityID', full_name='game.entity_message.entityID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='methodName', full_name='game.entity_message.methodName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm', full_name='game.entity_message.parm', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=88,
)


_VOID = _descriptor.Descriptor(
  name='void',
  full_name='game.void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['entity_message'] = _ENTITY_MESSAGE
DESCRIPTOR.message_types_by_name['void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

entity_message = _reflection.GeneratedProtocolMessageType('entity_message', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY_MESSAGE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.entity_message)
  })
_sym_db.RegisterMessage(entity_message)

void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.void)
  })
_sym_db.RegisterMessage(void)


DESCRIPTOR._options = None

_GAMESERVICE = _descriptor.ServiceDescriptor(
  name='GameService',
  full_name='game.GameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='entity_method',
    full_name='game.GameService.entity_method',
    index=0,
    containing_service=None,
    input_type=_ENTITY_MESSAGE,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVICE)

DESCRIPTOR.services_by_name['GameService'] = _GAMESERVICE

GameService = service_reflection.GeneratedServiceType('GameService', (_service.Service,), dict(
  DESCRIPTOR = _GAMESERVICE,
  __module__ = 'game_pb2'
  ))

GameService_Stub = service_reflection.GeneratedServiceStubType('GameService_Stub', (GameService,), dict(
  DESCRIPTOR = _GAMESERVICE,
  __module__ = 'game_pb2'
  ))


# @@protoc_insertion_point(module_scope)
